### ISSUE TITLE
Mic suddenly not working

### ISSUE THREAD

**Issue by bilogic** [maunolo/rusty-vban#5] opened 2023-10-03 12:54 UTC
Hi,

I don't really have anywhere else to turn to, so thought I give this a shot.

This receptor suddenly stopped working on my Windows 10. I reinstalled VoiceMeeter Banana for its VBAN to test and it is able to receive the stream. Any idea what might be the issue might be?

**Comment by maunolo** [comment] 2024-02-07 02:37
@bilogic
Do you have any logs, any errors?
Does it just stops without any messages in the console?

**Comment by bilogic** [comment] 2024-02-07 02:49
hey thanks for getting back, I don't recall if there were logs already. I switch back to using VMB.

**Comment by maunolo** [comment] 2024-02-07 04:28
I'm just asking because maybe is something related to your setup, on my setup I have a microfone and a headphone connected to a windows desktop and a linux laptop that I both send the microphone and receive the audio from, and I'm running this library on both machines to do that audio transfer.

I guess to fix the problem you had we would have to debug the packets sent or received by the program in your end.

**Comment by maunolo** [comment] 2024-03-09 18:50
Closing issue due to a lack of information to reproduce.

**Closed as completed by maunolo** 2024-03-09 18:50 UTC
